name: Android Publish
on:
  release:
    types: [created]

jobs:
  publish_apk:
    name: Publish APK Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Open Secret
        run: |
          mkdir $HOME/private
          gpg --quiet --batch --yes --decrypt --passphrase="$FIREBASE_SECRET" \
          --output $HOME/private/services.tar services.tar.gpg
          tar xvf $HOME/private/services.tar
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
      # Unit Test android
      - name: Unit Test the app
        run: ./gradlew test
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Upload Release APK
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ steps.sign_app.outputs.signedReleaseFile }}
          asset_name: tracker-covid.apk
          asset_content_type: application/zip
